name: Frontend deploy
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pnpm install
      run: pnpm install
    - name: npm run build
      run: npm run build
    - name: Deploy
      uses: cross-the-world/scp-pipeline@master
      with:
        host: ${{ secrets.USER_HOST }}
        user: ${{ secrets.USER_NAME }}
        pass: ${{ secrets.USER_PASS }}
        connect_timeout: 10s
        local: './dist/*'
        remote: /var/www/html/dist
